version: '3.9'
networks:
  default:
    name: infrastructure-net
    external: true

services:
  cardano-authentication:
    container_name: cardano-authentication
    image: cardano-authentication
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

      - EXPLORER_DB_SCHEMA=${EXPLORER_DB_SCHEMA}
      - EXPLORER_HOST=${EXPLORER_HOST}
      - EXPLORER_PORT=${EXPLORER_PORT}
      - EXPLORER_USER=${EXPLORER_USER}
      - EXPLORER_PASSWORD=${EXPLORER_PASSWORD}
      - EXPLORER_DB=${EXPLORER_DB}
      - EXPLORER_FLYWAY_ENABLE=${EXPLORER_FLYWAY_ENABLE}

      - SWAGGER_CLIENT_URL=${SWAGGER_CLIENT_URL}
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}

      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ROLE_MAPPING=${KEYCLOAK_ROLE_MAPPING}
      - KEYCLOAK_BEARER_ONLY=${KEYCLOAK_BEARER_ONLY}

      - RSA_PUBLIC_KEY_AUTH=${RSA_PUBLIC_KEY_AUTH}
      - RSA_PRIVATE_KEY_MAIL=${RSA_PRIVATE_KEY_MAIL}
      - RSA_PUBLIC_KEY_MAIL=${RSA_PUBLIC_KEY_MAIL}
      - SECRET_CODE=${SECRET_CODE}
    ports:
      - "${PORT}:8080"
    volumes:
      - $PWD/cardano/volumes/logs/cardano-authentication:/cardano-authentication/logs/
