version: '3.9'
networks:
  default:
    name: infrastructure-net
    external: true

services:
  cardano-authentication:
    container_name: cardano-authentication
    image: cardano-authentication
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - FLYWAY_ENABLED=${FLYWAY_ENABLED}

      - REDIS_SENTINEL_MASTER_NAME=${REDIS_SENTINEL_MASTER_NAME}
      - REDIS_SENTINEL_PASSWORD=${REDIS_SENTINEL_PASSWORD}
      - REDIS_SENTINEL_HOST=${REDIS_SENTINEL_HOST}
      - REDIS_SENTINEL_PORT=${REDIS_SENTINEL_PORT}
      - TIME_TO_LIVE_REDIS_SIGN_OUT=${TIME_TO_LIVE_REDIS_SIGN_OUT}

      - SWAGGER_CLIENT_URL=${SWAGGER_CLIENT_URL}
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}

      - KEYCLOAK_REALM_NAME=${KEYCLOAK_REALM_NAME}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ROLE_MAPPING=${KEYCLOAK_ROLE_MAPPING}
      - KEYCLOAK_BEARER_ONLY=${KEYCLOAK_BEARER_ONLY}

    ports:
      - "${PORT}:8080"
    volumes:
      - $PWD/cardano/volumes/logs/cardano-authentication:/cardano-authentication/logs/
