domain:
  client: http://localhost:3000
  server: http://localhost:8021

server:
  port: 8021

redis:
  databaseIndex: 0
  master: ${REDIS_MASTER_NAME:mymaster}
  password: ${REDIS_SENTINEL_PASS:redis_sentinel_pass}
  testOnBorrow: false
  maxTotal: 10
  maxIdle: 5
  minIdle: 3
  testOnReturn: false
  testWhileIdle: false
  sentinels:
    - host: ${REDIS_SENTINEL_HOST:localhost}
      port: 26379

keycloak:
  realm: ${KEYCLOAK_REALM_NAME:cardano_1}
  auth-server-url: ${KEYCLOAK_SERVER_URL:http://10.4.21.151:8080/}
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT_ID:client_1}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:mJvV0GtwiKUlpBZuNQ4Rmhxo3iY3JsRx}
  use-resource-role-mappings: ${KEYCLOAK_ROLE_MAPPING:true}
  bearer-only: ${KEYCLOAK_BEARER_ONLY:true}

timeToLiveRedisSignOut: ${TIME_TO_LIVE_REDIS_SIGN_OUT:48}

rsa:
  key:
    public-auth: ${RSA_PUBLIC_KEY_AUTH}
    private-mail: ${RSA_PRIVATE_KEY_MAIL}
    public-mail: ${RSA_PUBLIC_KEY_MAIL}
