spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: test.sotatek1@gmail.com
    password: zcphnnfpneuuoalv
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: info

mail:
  from: 'test.sotatek1@gmail.com'
  sender: 'Sotatek'
  subject-registration: 'Please verify your registration'
  subject-reset-password: 'Do you want change password?'
  footer: 'The Sotatek company'
  expirationMs: 86400000 #1 day

thread-pool:
  core-size: 5
  max-size: 20
  queue-size: 100
  timeout: 10
