domain:
  client: http://localhost:3000
  server: http://localhost:8021

server:
  port: 8021

redis:
  databaseIndex: 0
  master: ${REDIS_MASTER_NAME:mymaster}
  password: ${REDIS_SENTINEL_PASS:redis_sentinel_pass}
  testOnBorrow: false
  maxTotal: 10
  maxIdle: 5
  minIdle: 3
  testOnReturn: false
  testWhileIdle: false
  sentinels:
    - host: ${REDIS_SENTINEL_HOST:localhost}
      port: 26379

keycloak:
  realm: ${KEYCLOAK_REALM_NAME:cardano_authen}
  auth-server-url: ${KEYCLOAK_SERVER_URL:http://10.4.21.151:8080/}
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT_ID:client_test}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:LuJVyHvOipnRFFAWO7AnUFWkyKCJ3ax4}
  use-resource-role-mappings: ${KEYCLOAK_ROLE_MAPPING:true}
  bearer-only: ${KEYCLOAK_BEARER_ONLY:true}

timeToLiveRedisSignOut: ${TIME_TO_LIVE_REDIS_SIGN_OUT:48}