spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info

rsa:
  key:
    private-key-file: /key/private_key
    public-key-file: /key/public_key

jwt:
  expirationMs: 86400000 #24 hours
  refreshExpirationMs: 172800000 #48 hours

nonce:
  expirationMs: 172800000 #48 hours
