domain:
  client: ${SWAGGER_CLIENT_URL:http://localhost:7276}
  server: ${SWAGGER_SERVER_URL:http://localhost:8021}

redis:
  databaseIndex: 0
  master: ${REDIS_SENTINEL_MASTER_NAME:mymaster}
  password: ${REDIS_SENTINEL_PASSWORD:redis_sentinel_password}
  testOnBorrow: false
  maxTotal: 10
  maxIdle: 5
  minIdle: 3
  testOnReturn: false
  testWhileIdle: false
  sentinels:
    - host: ${REDIS_SENTINEL_HOST:127.0.0.1}
      port: ${REDIS_SENTINEL_PORT:26379}

keycloak:
  realm: ${KEYCLOAK_REALM_NAME:cardano_authen}
  auth-server-url: ${KEYCLOAK_SERVER_URL:http://10.4.21.151:8080/}
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT_ID:client_test}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:LuJVyHvOipnRFFAWO7AnUFWkyKCJ3ax4}
  use-resource-role-mappings: ${KEYCLOAK_ROLE_MAPPING:true}
  bearer-only: ${KEYCLOAK_BEARER_ONLY:true}

timeToLiveRedisSignOut: ${TIME_TO_LIVE_REDIS_SIGN_OUT:48}

rsa:
  key:
    public-auth: ${RSA_PUBLIC_KEY_AUTH}
    private-mail: ${RSA_PRIVATE_KEY_MAIL}
    public-mail: ${RSA_PUBLIC_KEY_MAIL}
<<<<<<< HEAD

=======
>>>>>>> df4fc1c9403092c4b3ed48417ab5c44a63c526c0
