spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: localhost
    port: 6379
    timeout: 3000ms

logging:
  level:
    root: info

rsa:
  key:
    private-key-file: /key/private_key
    public-key-file: /key/public_key

jwt:
  expirationMs: 3600000 #60 minutes
  refreshExpirationMs: 7200000 #120 minutes

nonce:
  expirationMs: 43200000 #12 hours
