spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: localhost
    port: 6379
    timeout: 3000ms

server:
  port: 8021

logging:
  level:
    root: info

rsa:
  key:
    rsa-key-file: /key/rsa_key

jwt:
  expirationMs: 300000 #5 minutes
  refreshExpirationMs: 600000 #10 minutes

nonce:
  expirationMs: 43200000 #12 hours
